### PR TITLE
Add Transparency Mode badge

### PR DESCRIPTION
**Pull request by cjdenio**
idk if this should actually go here, but it felt cool

### CODE REVIEW

**Review by exu3 — APPROVED** [review]
Yeah! Or maybe the Finances section? https://github.com/hackclub/the-hacker-zephyr#-finances

**Comment by cjdenio** [comment]
@sampoder thoughts?

**Comment by sampoder** [comment]
My only worry is that eventually that number should become $0, and then it's kind of redundant

**Comment by cjdenio** [comment]
hmm, true.

**Pull request closed without merging**
